import os
import glob
import shutil

symbols = ['3MINDIA', 'AARTIDRUGS', 'AARTIIND', 'ABAN', 'ABB', 'ABBOTINDIA', 'ACC', 'ADANIENT', 'ADANIPORTS',
           'ADANIPOWER', 'AEGISCHEM', 'AHLUCONT', 'AIAENG', 'AJANTPHARM', 'AKZOINDIA', 'ALKYLAMINE', 'ALLCARGO',
           'AMARAJABAT', 'AMBUJACEM', 'ANANTRAJ', 'APARINDS', 'APLAPOLLO', 'APLLTD', 'APOLLOHOSP', 'APOLLOTYRE',
           'APTECHT', 'ARVIND', 'ASAHIINDIA', 'ASHIANA', 'ASHOKA', 'ASHOKLEY', 'ASIANPAINT', 'ASTRAL', 'ASTRAZEN',
           'ATFL', 'ATUL', 'AUROPHARMA', 'AUTOAXLES', 'AUTOIND', 'AVANTIFEED', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJCON',
           'BAJAJELEC', 'BAJAJFINSV', 'BAJAJHIND', 'BAJAJHLDNG', 'BAJFINANCE', 'BALAMINES', 'BALKRISIND', 'BALMLAWRIE',
           'BALRAMCHIN', 'BANARISUG', 'BANKBARODA', 'BANKINDIA', 'BASF', 'BATAINDIA', 'BAYERCROP', 'BBTC', 'BEL',
           'BEML', 'BERGEPAINT', 'BFUTILITIE', 'BGRENERGY', 'BHARATFORG', 'BHARTIARTL', 'BHEL', 'BIOCON', 'BIRLACORPN',
           'BLISSGVS', 'BLUEDART', 'BLUESTARCO', 'BOMDYEING', 'BOSCHLTD', 'BPCL', 'BRIGADE', 'BRITANNIA', 'BSOFT',
           'CANBK', 'CANFINHOME', 'CARBORUNIV', 'CASTROLIND', 'CCL', 'CEATLTD', 'CENTENKA', 'CENTRALBK', 'CENTURYPLY',
           'CENTURYTEX', 'CERA', 'CESC', 'CGCL', 'CGPOWER', 'CHAMBLFERT', 'CHENNPETRO', 'CHOLAFIN', 'CIPLA',
           'COALINDIA', 'COFORGE', 'COLPAL', 'CONCOR', 'COROMANDEL', 'CRISIL', 'CUB', 'CUMMINSIND', 'CYIENT', 'DABUR',
           'DBCORP', 'DBREALTY', 'DCBBANK', 'DCMSHRIRAM', 'DCW', 'DEEPAKFERT', 'DEEPAKNTR', 'DELTACORP', 'DEN',
           'DHANBANK', 'DHANUKA', 'DISHTV', 'DIVISLAB', 'DLF', 'DREDGECORP', 'DRREDDY', 'DYNAMATECH', 'ECLERX',
           'EDELWEISS', 'EICHERMOT', 'EIDPARRY', 'EIHOTEL', 'ELECTCAST', 'ELGIEQUIP', 'EMAMILTD', 'ENGINERSIN', 'ENIL',
           'EPL', 'EROSMEDIA', 'ESABINDIA', 'ESCORTS', 'EVEREADY', 'EXIDEIND', 'FACT', 'FDC', 'FEDERALBNK', 'FINCABLES',
           'FINPIPE', 'FLEXITUFF', 'FMGOETZE', 'FORTIS', 'FSL', 'GABRIEL', 'GAEL', 'GAIL', 'GARFIBRES', 'GATI', 'GEPIL',
           'GESHIP', 'GHCL', 'GILLETTE', 'GIPCL', 'GLAXO', 'GLENMARK', 'GMDCLTD', 'GMRINFRA', 'GNFC', 'GODFRYPHLP',
           'GODREJCP', 'GODREJIND', 'GODREJPROP', 'GPPL', 'GRANULES', 'GRAPHITE', 'GRASIM', 'GREAVESCOT', 'GREENPLY',
           'GRINDWELL', 'GSFC', 'GSPL', 'GTLINFRA', 'GUJALKALI', 'HATHWAY', 'HAVELLS', 'HCC', 'HCL-INSYS', 'HCLTECH',
           'HDFC', 'HDFCBANK', 'HEG', 'HEIDELBERG', 'HERITGFOOD', 'HEROMOTOCO', 'HFCL', 'HGS', 'HIKAL', 'HIMATSEIDE',
           'HINDALCO', 'HINDCOPPER', 'HINDOILEXP', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'HMVL', 'HONAUT', 'HSCL',
           'HTMEDIA', 'IBREALEST', 'ICICIBANK', 'ICIL', 'ICRA', 'IDBI', 'IDEA', 'IDFC', 'IFBIND', 'IFCI', 'IGARASHI',
           'IGL', 'IIFL', 'IMFA', 'INDHOTEL', 'INDIACEM', 'INDIAGLYCO', 'INDIANB', 'INDOCO', 'INDUSINDBK', 'INFY',
           'INGERRAND', 'IOB', 'IOC', 'IPCALAB', 'IRB', 'ITC', 'ITDCEM', 'ITI', 'J&KBANK', 'JAGRAN', 'JAICORPLTD',
           'JAMNAAUTO', 'JBCHEPHARM', 'JBMA', 'JCHAC', 'JINDALPOLY', 'JINDALSAW', 'JINDALSTEL', 'JINDWORLD',
           'JISLJALEQS', 'JKCEMENT', 'JKIL', 'JKLAKSHMI', 'JKPAPER', 'JKTYRE', 'JMFINANCIL', 'JPASSOCIAT', 'JPPOWER',
           'JSL', 'JSWENERGY', 'JSWHL', 'JSWSTEEL', 'JUBLFOOD', 'JUBLPHARMA', 'JYOTHYLAB', 'KAJARIACER', 'KANSAINER',
           'KARURVYSYA', 'KCP', 'KEC', 'KEI', 'KESORAMIND', 'KIRLOSENG', 'KKCL', 'KNRCON', 'KOLTEPATIL', 'KOTAKBANK',
           'KPIL', 'KPRMILL', 'KRBL', 'KSB', 'KSCL', 'KTKBANK', 'L&TFH', 'LAOPALA', 'LAXMIMACH', 'LGBBROSLTD',
           'LICHSGFIN', 'LINDEINDIA', 'LOVABLE', 'LT', 'LUPIN', 'M&M', 'M&MFIN', 'MAHABANK', 'MAHLIFE', 'MAHSCOOTER',
           'MAHSEAMLES', 'MANAPPURAM', 'MANGCHEFER', 'MANINDS', 'MANINFRA', 'MARICO', 'MARKSANS', 'MARUTI', 'MASTEK',
           'MCDOWELL-N', 'MCLEODRUSS', 'MCX', 'MFSL', 'MHRIL', 'MINDACORP', 'MMTC', 'MOIL', 'MOTHERSON', 'MOTILALOFS',
           'MPHASIS', 'MRF', 'MRPL', 'MTNL', 'MUNJALSHOW', 'MUTHOOTFIN', 'NATCOPHARM', 'NATIONALUM', 'NAUKRI',
           'NAVINFLUOR', 'NAVNETEDUL', 'NBCC', 'NCC', 'NDTV', 'NESCO', 'NESTLEIND', 'NETWORK18', 'NFL', 'NHPC',
           'NIITLTD', 'NILKAMAL', 'NLCINDIA', 'NMDC', 'NOCIL', 'NOIDATOLL', 'NTPC', 'OBEROIRLTY', 'OFSS', 'OIL',
           'OLECTRA', 'OMAXE', 'ONELIFECAP', 'ONGC', 'ORISSAMINE', 'PAGEIND', 'PARSVNATH', 'PCBL', 'PEL', 'PENIND',
           'PENINLAND', 'PERSISTENT', 'PETRONET', 'PFC', 'PFIZER', 'PFOCUS', 'PFS', 'PGHH', 'PGHL', 'PHOENIXLTD',
           'PIDILITIND', 'PIIND', 'PNB', 'POLYMED', 'POLYPLEX', 'POONAWALLA', 'POWERGRID', 'PRAJIND', 'PRAKASH',
           'PRESTIGE', 'PTC', 'PURVA', 'PVRINOX', 'RADICO', 'RAIN', 'RAJESHEXPO', 'RALLIS', 'RAMCOCEM', 'RAMCOIND',
           'RAMCOSYS', 'RAMKY', 'RATNAMANI', 'RAYMOND', 'RCF', 'RECLTD', 'REDINGTON', 'RELAXO', 'RELIANCE', 'RELIGARE',
           'RELINFRA', 'RENUKA', 'RHIM', 'RIIL', 'RKFORGE', 'RPOWER', 'RTNPOWER', 'RUPA', 'SAIL', 'SANOFI', 'SBIN',
           'SCHAEFFLER', 'SCHNEIDER', 'SCI', 'SHANTIGEAR', 'SHILPAMED', 'SHOPERSTOP', 'SHREECEM', 'SHRIRAMFIN',
           'SIEMENS', 'SIMPLEXINF', 'SJVN', 'SKFINDIA', 'SMLISUZU', 'SOBHA', 'SOLARINDS', 'SOMANYCERA', 'SONATSOFTW',
           'SOUTHBANK', 'SPARC', 'SRF', 'STAR', 'STCINDIA', 'STLTECH', 'SUDARSCHEM', 'SUNCLAYLTD', 'SUNDARMFIN',
           'SUNDRMFAST', 'SUNPHARMA', 'SUNTECK', 'SUNTV', 'SUPRAJIT', 'SUPREMEIND', 'SUVEN', 'SUZLON', 'SWANENERGY',
           'SWARAJENG', 'SYMPHONY', 'TAKE', 'TANLA', 'TATACHEM', 'TATACOFFEE', 'TATACOMM', 'TATACONSUM', 'TATAELXSI',
           'TATAINVEST', 'TATAMOTORS', 'TATAMTRDVR', 'TATAPOWER', 'TATASTEEL', 'TBZ', 'TCS', 'TDPOWERSYS', 'TECHM',
           'TEXRAIL', 'THERMAX', 'THOMASCOOK', 'TIDEWATER', 'TIMETECHNO', 'TIMKEN', 'TINPLATE', 'TITAN', 'TNPL',
           'TORNTPHARM', 'TORNTPOWER', 'TREEHOUSE', 'TRENT', 'TRIDENT', 'TRITURBINE', 'TRIVENI', 'TTKPRESTIG', 'TTML',
           'TV18BRDCST', 'TVSMOTOR', 'TVSSRICHAK', 'TVTODAY', 'UBL', 'UCOBANK', 'UFLEX', 'ULTRACEMCO', 'UNICHEMLAB',
           'UNIONBANK', 'UNOMINDA', 'UPL', 'USHAMART', 'VAIBHAVGBL', 'VAKRANGEE', 'VEDL', 'VENKEYS', 'VESUVIUS',
           'VGUARD', 'VINATIORGA', 'VIPIND', 'VOLTAS', 'VSTIND', 'VTL', 'WABAG', 'WELCORP', 'WELSPUNIND', 'WHEELS',
           'WHIRLPOOL', 'WIPRO', 'WOCKPHARMA', 'WSTCSTPAPR', 'YESBANK', 'ZEEL', 'ZENSARTECH', 'ZODIACLOTH', 'ZYDUSLIFE',
           'ZYDUSWELL']

folder = glob.glob('D:/CSV/*')

for sym in folder:
    src = sym.split('\\')[0]
    symbol = sym.split('\\')[1]
    dest = src + '/' + 'all_data'
    if symbol in symbols:
        print(symbol)
        shutil.move(sym, dest)

